name = "postgleam"
version = "0.1.0"
description = "A native Gleam PostgreSQL driver implementing the wire protocol"
licences = ["Apache-2.0"]
repository = { type = "github", user = "uncle-samm", repo = "postgleam" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 3.0.0"
gleam_erlang = ">= 1.0.0 and < 3.0.0"
gleam_otp = ">= 0.16.0 and < 2.0.0"
gleam_crypto = ">= 1.0.0 and < 3.0.0"
gleam_json = ">= 3.0.0 and < 5.0.0"
mug = ">= 3.0.0 and < 5.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 3.0.0"
